spring:
  profiles:
    active: dev
  datasource:
    url: "jdbc:postgresql://127.0.0.1:5432/financial-targets-db"
    username: postgres
    password: G~w<Yq=&fU;93kNLZ
  jpa:
    hibernate:
      ## ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
server:
  port: 8081
  servlet:
    contextPath: /api
  info:
    app:
      name: Financial Targets Outflow Service
      version: '0.0.1-SNAPSHOT'
logging:
  level:
    root: INFO
    com.financialtargets: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
  file:
    name: outflow-service.log
    max-size: 10MB
    max-history: 30
  # — Exemplo de configuração com Logstash JSON Encoder (se usar)
    # logging:
    #   level:
    #     root: INFO
    #     com.financialtargets: DEBUG
    #   file:
    #     name: outflow-service-json.log
    #     max-size: 10MB
    #     max-history: 30
    #   logstash:
    #     enabled: true
    #     encoder.pattern: |
    #       {
    #         "timestamp": "%date{ISO8601}",
    #         "level": "%level",
    #         "thread": "%thread",
    #         "logger": "%logger",
    #         "message": "%message",
    #         "context": "%mdc"
    #       }