spring:
  profiles:
    active: dev
  datasource:
    url: "jdbc:postgresql://127.0.0.1:5432/financial-targets-db"
    username: postgres
    password: G~w<Yq=&fU;93kNLZ

server:
  port: 8081
  servlet:
    contextPath: /api

  info:
    app:
      name: Financial Targets Outflow Service
      version: '0.0.1-SNAPSHOT'